const express = require("express");
const userRoutes = require("./userRoutes");
const authRoutes = require("./authRoutes");
const extensionRoutes = require("./extensionRoutes");
const amiRoutes = require("./amiRoutes");
const pjsipAuthRoutes = require("./pjsip_authsRoutes");
const pjsipAorsRoutes = require("./pjsip_aorsRoutes");
const pjsipEndpointsRoutes = require("./pjsip_endpointsRoutes");
const adminDashboardRoutes = require("./adminDashboard");
const voiceRoutes = require("./voiceRoutes");
const ivrActionRoutes = require("./ivrActionRoutes");
const recordingRoutes = require("./recordingRoutes");
const ticketRoutes = require("./ticketRoutes");
const reviewerRoutes = require("./reviewerRoutes");
const sectionRoutes = require("./sectionRoutes");
const channelRoutes = require("./channelRoutes");
const getCallsRoutes = require("./callsRoutes");
const macRoutes = require("./macRoutes");
const notificationRoutes = require("./notificationRoutes");
const complaintWorkflowRoutes = require("./complaintWorkflowRoutes");
const focalPersonRoutes = require("./focalPersonRoutes");
const instagramComments = require("./instagramWebhookRoutes");
const performanceRoutes = require("./performanceRoutes");
const workflowRoutes = require("./workflowRoutes");
const externalRoutes = require("./externalRoutes");
const esspRoutes = require("./esspRoutes");
const lookupTableRoutes = require("./lookupTableRoutes");
const ticketUpdateRoutes = require("./ticketUpdateRoutes");
const ticketChartRoutes = require("./ticketChartRoutes");
const ticketSummaryRoutes = require("./ticketSummaryRoutes");
const callSummaryRoutes = require("./callSummaryRoutes");
const logRoutes = require("./logRoutes");
const router = express.Router();
// const monitorRoutes = require("./monitorRoutes");
const missedCallRoutes = require("./missedCallRoutes");
const queueStatusRoutes = require("./queueStatusRoutes");
const livestreamRoutes = require("./livestreamRoutes");
const publicDashboardRoutes = require("./publicDashboardRoutes");
const reportsRoutes = require("./reports.routes");

router.use("/users", userRoutes);
router.use("/auth", authRoutes);
router.use("/extensions", extensionRoutes);
router.use("/ami", amiRoutes);
router.use("/pjsip_auths", pjsipAuthRoutes);
router.use("/pjsip_aors", pjsipAorsRoutes);
router.use("/pjsip_endpoints", pjsipEndpointsRoutes);
router.use("/admin-dashboard", adminDashboardRoutes);
router.use("/ivr", voiceRoutes);
router.use("/ivr-actions", ivrActionRoutes);
// voice-notes API mounted in server.js at /api/voice-notes
router.use("/ticket", ticketRoutes);
router.use("/reviewer", reviewerRoutes);
router.use("/section", sectionRoutes);
router.use("/channel", channelRoutes);
router.use("/calls", getCallsRoutes);
router.use("/mac-system", macRoutes);
// router.use("/monitor", monitorRoutes);
router.use("/missed-calls", missedCallRoutes);
router.use("/performance", performanceRoutes);
router.use("/queue-status", queueStatusRoutes);
router.use("/livestream", livestreamRoutes);
router.use("/public", publicDashboardRoutes);
router.use("/workflow", workflowRoutes);
router.use("/external", externalRoutes);
router.use("/essp", esspRoutes);
router.use("/ticket-updates", ticketUpdateRoutes);
router.use("/ticket-charts", ticketChartRoutes);
router.use("/ticket-summary", ticketSummaryRoutes);
router.use("/call-summary", callSummaryRoutes);

router.use("/notifications", notificationRoutes);
router.use("/complaints", complaintWorkflowRoutes);
router.use("/focal-person", focalPersonRoutes);
router.use("/lookup-tables", lookupTableRoutes);
router.use("/reports", reportsRoutes);
router.use("/logs", logRoutes);
router.use("/", instagramComments);

module.exports = router;
